yasanori/freemarket_sample_71a

Capfile
Gemfile
Gemfile.lock
README.md
config/deploy.rb
config/deploy/production.rb
config/deploy/staging.rb

#What
capistrano導入のための事前準備。
production.rb、
deploy.rbの編集
#Why
githubレポジトリや、Elastic IPアドレスの一部設定に必要な情報が既にあったため。
今後自動デプロイの際、作業を減らすことが目的

capistrano setting

---

config/database.yml

Change description

---

config/unicorn.rb

#What
capistro導入のため
unicorn.rbの編集を行なった

add_capistro_unicorn.rb

---

app/assets/stylesheets/_aside.scss
app/assets/stylesheets/_footer.scss
app/assets/stylesheets/_header.scss
app/assets/stylesheets/_purchase-btn.scss
app/assets/stylesheets/_sec1.scss
app/assets/stylesheets/_sec3.scss
app/assets/stylesheets/_sec4.scss
app/assets/stylesheets/application.scss
app/views/tests/index.html.haml

#What
header ,section3~5,aside,footer,fixedbtn のビュー作成。
リンク先はなし。

top pag, header, sec3 ~ 5, aside,footer,fixedbtn

---

app/controllers/application_controller.rb
config/deploy/production.rb

Basic認証の記述の追加
サンプルで作成したサイトにパスワード認証機能をつけるため。

BASIC認証記述追加

---

app/assets/stylesheets/_header.scss
app/assets/stylesheets/_sec0.scss
app/assets/stylesheets/application.scss

top-page-fix

---

app/controllers/application_controller.rb
app/controllers/users/confirmations_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb
app/controllers/users/passwords_controller.rb
app/controllers/users/registrations_controller.rb
app/controllers/users/sessions_controller.rb
app/controllers/users/unlocks_controller.rb
app/controllers/users_controller.rb
app/models/address.rb
app/models/card.rb
app/models/user.rb
config/routes.rb
db/migrate/20200320063819_create_cards.rb
db/schema.rb

#What
Sign_up をsessionを使用して行うため
メソッドを定義した。
ユーザー情報と本人確認、addressのそれぞれの登録。
#Why
利便性の向上

Devise model setting

---

app/assets/stylesheets/items/_items.scss
app/views/items/index.html.haml

アイテム購入ページ,確認ぺーじの作成
今後実装する機能のviewの部分の骨組み作成。

アイテム詳細ページ、購入ページ

---

app/controllers/users/registrations_controller.rb
app/models/address.rb
app/models/categories.rb
app/models/commodity_condition.rb
app/models/item.rb
app/models/prefecture.rb
app/models/shipping_charge.rb
app/models/shipping_day.rb
app/models/shipping_method.rb
app/models/size.rb
app/views/devise/registrations/new.html.haml
app/views/items/new.html.haml
db/migrate/20200320034142_create_addresses.rb
db/migrate/20200320063819_create_cards.rb
db/migrate/20200320111950_create_items.rb
db/migrate/20200323092208_remove_card_company_card_numbercard_year_card_month_from_cards.rb
db/migrate/20200323092429_add_customer_id_card_id_to_cards.rb
db/schema.rb

Item images/new2

---

app/assets/stylesheets/_item_share.scss
app/controllers/items_controller.rb
app/uploaders/image_uploader.rb
app/views/items/index.html.haml
config/initializers/carrierwave.rb

キャリーウェーブの保存先ローカルでの指定変更。
index itempage

fix carrywave update

---

app/models/item.rb
app/views/devise/registrations/new.html.haml
app/views/devise/sessions/new.html.haml

新規登録画面、ログイン画面のマークアップを行った。 
フリマアプリにおいて新規登録画面、ログイン画面の実装は必須な為

ユーザー新規登録、ログインページマークアップ

---

app/views/items/index.html.haml
app/views/shared/_item.html.haml

部分テンプレート微調整

---

app/controllers/items_controller.rb
app/views/items/show.html.haml

#What
商品の詳細表示画面を作成し、そのページに出品者のみに表示させることができる削除ボタンを作成した。
items_controller.rb show/destroy
items/show.html.haml
#Why
必須機能であるため

code-review(delete/show)

---

app/controllers/card_controller.rb
app/controllers/purchase_controller.rb

binding remove

---

app/assets/stylesheets/card.scss
app/views/card/new.html.haml
app/views/card/show.html.haml
app/views/purchase/done.html.haml
app/views/purchase/index.html.haml

購入画面の支払いまでの過程viewを整えました
使いやすくするため

pay.jp購入機能の見た目ひとまず

---

app/assets/stylesheets/items/_item_show.scss
app/controllers/items_controller.rb
app/views/items/show.html.haml

#What
登録できたカテゴリーを、商品詳細ページで表示させた。
また。表示内容としてancestryを使用して親カテゴリーも表示させた。

詳細表示、カテゴリーのひょうじ

---

app/controllers/items_controller.rb
app/controllers/purchase_controller.rb

商品購入機能の実装。
複数人で作り、途中マージあるため完了報告になります。
フリマアプリ作成のため

add-buy-function

---

app/models/brand.rb
app/models/item.rb
app/views/items/edit.html.haml
app/views/items/new.html.haml
app/views/items/show.html.haml

#What
ブランドモデルにデータを記入した。
出品、編集で使用。
アクティブハッシュ。
#Why
出品ページに
直接書き込むと冗長になるため。

brand-data

---

app/assets/javascripts/frema_index_header.js
app/assets/stylesheets/moduls/_header.scss
app/views/shared/_header.html.haml

カテゴリータブクリックでカテゴリーが表示される。
ヘッダー部分CSSアニメーションの追加
hover時アンダーライン
フロントコメントアウト箇所必要ないものの削除
UIを考慮し少しでもわかりやすくするための修正

ヘッダーカテゴリー機能追加

---

app/assets/javascripts/guest_sessions.coffee
app/assets/stylesheets/application.scss
app/assets/stylesheets/devise/registrations/_new_address.scss
app/assets/stylesheets/guest_sessions.scss
app/assets/stylesheets/items/_item_new.scss
app/controllers/application_controller.rb
app/controllers/guest_sessions_controller.rb
app/controllers/users/registrations_controller.rb
app/helpers/guest_sessions_helper.rb
app/views/devise/sessions/new.html.haml
config/routes.rb
test/controllers/guest_sessions_controller_test.rb

ゲストユーザーのログイン機能
簡易版
作成済みアカウンロをセッションへ直接ボタンから遷移できるボタンの作成。
ログイン入力の手間をなくすため

ゲストーユーザーログイン機能

---

app/assets/javascripts/brand.js
app/assets/javascripts/categorys.coffee
app/assets/javascripts/comments.coffee
app/assets/stylesheets/brands.scss
app/assets/stylesheets/moduls/_header.scss
app/controllers/application_controller.rb
app/controllers/brands_controller.rb
app/controllers/tests_controller.rb
app/helpers/brands_helper.rb
app/views/brands/show.html.haml
app/views/shared/_header.html.haml
config/routes.rb
spec/helpers/brands_helper_spec.rb
spec/requests/brands_request_spec.rb

brand-seach

---

app/controllers/items_controller.rb
app/views/devise/registrations/new.html.haml
app/views/items/edit.html.haml

#What
fileds_forを変更
#Why
商品情報編集時に商品画像を削除しても、テーブルから削除する事ができなかったため。

editのエラー解消

---

app/controllers/application_controller.rb
app/controllers/guest_sessions_controller.rb
config/deploy/production.rb

ゲストログイン機能でエラーハンドリングの実装
ゲストアカウントが存在しない場合にはflashを表示させてindexへリダイレクト
永尾さん修正ありがとうございます＾＾
Co-Authored-By: nagao <yasanori@users.noreply.github.com>

ゲストログイン機能のエラーハンドリング
